// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDho2mhCVG20aGpWX84837QXaDsFT2N8g4',
    appId: '1:617349292898:web:a6b4fc117f324ea5d7823b',
    messagingSenderId: '617349292898',
    projectId: 'kigalicity-f08ec',
    authDomain: 'kigalicity-f08ec.firebaseapp.com',
    storageBucket: 'kigalicity-f08ec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvIQ2Ehwkqj03zDTTXtyQBIkCs89D30QY',
    appId: '1:617349292898:android:cdc36a975dc99879d7823b',
    messagingSenderId: '617349292898',
    projectId: 'kigalicity-f08ec',
    storageBucket: 'kigalicity-f08ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNpsfShC6hAEVtCW-AvvWkRABF3j_pMl4',
    appId: '1:617349292898:ios:bbc91aef0d0126e6d7823b',
    messagingSenderId: '617349292898',
    projectId: 'kigalicity-f08ec',
    storageBucket: 'kigalicity-f08ec.firebasestorage.app',
    iosBundleId: 'com.example.kigalicityservices',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNpsfShC6hAEVtCW-AvvWkRABF3j_pMl4',
    appId: '1:617349292898:ios:bbc91aef0d0126e6d7823b',
    messagingSenderId: '617349292898',
    projectId: 'kigalicity-f08ec',
    storageBucket: 'kigalicity-f08ec.firebasestorage.app',
    iosBundleId: 'com.example.kigalicityservices',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDho2mhCVG20aGpWX84837QXaDsFT2N8g4',
    appId: '1:617349292898:web:996b6bd4c79589f8d7823b',
    messagingSenderId: '617349292898',
    projectId: 'kigalicity-f08ec',
    authDomain: 'kigalicity-f08ec.firebaseapp.com',
    storageBucket: 'kigalicity-f08ec.firebasestorage.app',
  );
}
